### ISSUE TITLE
How can I test a StorageController?

### ISSUE THREAD

**Issue by jmichas** [Azure/azure-mobile-apps-net-files-server#13]
I'm not sure what values I should be using for a StorageTokenRequest and MobileServiceFile.

I'd like to be able to unit test my controller actions using a dummy text file but the details of the calls from the client to the server are not easily available.

What should the request ProviderName be?
What should most of the MobileServiceFile properties be set to?

**Comment by lindydonna** [comment]
FYI, you can see the calls from the client to the server by using Fiddler or attaching a [LoggingHandler](https://github.com/Azure-Samples/app-service-mobile-dotnet-todo-list-files/blob/master/src/client/MobileAppsFilesSample/Helpers/LoggingHandler.cs#L63).

You don't need to fill in all of the properties for the StorageTokenRequest. You just need the Permissions and the fields Id, Name, TableName, and ParentID for the MobileServiceFile, such as:

    { 
      "Permissions": "Read", 
      "TargetFile": 
        {
            "Id": "XXX",
            "Name": "XXX",
            "TableName": "Image",
            "ParentId": "YYY",        
        }
    }
