### ISSUE TITLE
Container per table with subfolder per entity

### ISSUE THREAD

**Issue by bledbet** [Azure/azure-mobile-apps-net-files-server#8]
I would like to modify behavior such that all files associated with a given table all end up under the same container, just in separate folders.  This is because we want to open GET access to blobs associated with this table (other tables would remain secure) without having to change the access settings for every container.

I see that I can inject my own implementation of IContainerNameResolver, and was hoping that
       
```
private string GetDefaultContainerName(string tableName, string recordId)
        {
            return string.Format("{0}/{1}", tableName, recordId).ToLower();
        }
```

would have the desired effect, but I get a "bad request" - is there any chance that there's something I'm missing that would allow me to accomplish organizing my files in folders under a single container?

**Comment by lindydonna** [comment]
That should work, but it's possible that there's some other dependency that's at play here. Take a look at https://github.com/Azure/azure-mobile-apps-net-files-server/blob/master/src/Microsoft.Azure.Mobile.Server.Files/StorageProviders/AzureStorageProvider.cs and see if it has some assumptions about folder name. You may need to provide your own implementation of AzureStorageProvider as well.

**Comment by bledbet** [comment]
Thanks for your suggestion, Donna.

After reviewing the code for AzureStorageProvider in the Server.Files project, it looks like I could create a custom implementation that I could inject a custom IContainerNameResolver into (that would resolve a single container for all entities of a certain type), and could come up with my own IFolderNameResolver construct to inject into it to get to a specific entity's folder within that container.

However, this alone would only work for GET's and DELETE's - the MobileServiceFilesClient doesn't go through the server-side StorageController for PUT's/POST's - it uses a client side StorageProvider to go directly to the storage account.  Unfortunately, this means that the logic for specifying where the files go in the storage account has to be implemented in two places, complicating the solution.  Let me know if it seems to you that I have misunderstood.

Do you think that in the future the MobileServiceFilesClient will call the server-side StorageController to upload the files?  It seems like this would encapsulate the file storage layer better, and make a customized solution like this simpler.

**Comment by bledbet** [comment]
Actually, I think I see now that before the Client uploads a file, it has to call the server's StorageController to get a StorageToken, and the path determination happens there and is included as a property of the returned StorageToken, so the path determination logic should be able to all stay centralized in a custom server-side StorageProvider.

I think I also see the reason for the design decision to use a container per entity though, now, and will instead look for a way to make opening container permissions manageable.

**Comment by lindydonna** [comment]
That's right, the client makes a request to the server and gets the SAS token and the blob location. However, you do raise a good point, that even though there is a container name resolver, it assumes that you are generally mapping one record to one container. I'll create a separate issue to track that.
