### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by jiberan** [Azure/azure-mobile-apps-net-files-server#9]
Are you still working on RTM? There hasn't been commit for more then 4 months. Thanks.

**Comment by fabiocav** [comment]
@jiberan things have been a little quiet here, but we've been actively collecting feedback from customers and other teams using the SDK. We'll be working on the next milestone planning. I don't have exact dates, but planning and execution will be public on this repo. In the meantime, if you have any issues impacting you, please make sure am issue is opened so we can address it. Thanks!
